version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    ports:
      - 3000:3000
  backend:
    depends_on: db
    ports:
      - 8080:8080
    environment:
      - DB_URL=db
  db:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - D:\MyMusicApp\dataDb:/var/lib/mysql

volumes:
  MyMusic: